### ISSUE TITLE
Make the start function, resume function and lastly the reset function

### ISSUE THREAD

**Issue by AlzynJosselCellero** [AlzynJosselCellero/CODEgo#3]
Research it on the internet

**Comment by castro1234** [comment]
# start, pause, lap, and resume functions
def start():
    global running
    if not running:
        update()
        running = True

# resume function    
def resume():
    global running
    if not running:
        update()
        running = True

# reset function
def reset():
    global running
    if running:
        # cancelling updating of time using after_cancel()
        stopwatch.after_cancel(update_time)
        running = False
    # set variables back to zero
    global hours, minutes, seconds
    hours, minutes, seconds = 0, 0, 0
    # set label back to zero
    stopwatch.config(text="00:00:00")
